### ISSUE TITLE
add liteX and migen platform

### ISSUE THREAD

**Issue by dangbinghoo** [suryakantamangaraj/awesome-riscv-resources#2]
the list forget  liteX and migen(nmigen) platform ^_^

**Comment by suryakantamangaraj** [comment]
Thank you for pointing out the omission of the liteX and migen(nmigen) platforms. 
Your input is valuable to us. We encourage you to contribute to the list by following the guidelines provided in the [contribution link](https://github.com/suryakantamangaraj/AwesomeRISC-VResources/blob/master/Contributing.md). Your expertise and knowledge would be a great addition to our resources. 😊
